CREATE TABLE IF NOT EXISTS diagrams (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS nodes (
  id SERIAL PRIMARY KEY,
  diagram_id INT NOT NULL REFERENCES diagrams(id) ON DELETE CASCADE,
  label TEXT NOT NULL,
  x DOUBLE PRECISION NOT NULL,
  y DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS edges (
  id SERIAL PRIMARY KEY,
  diagram_id INT NOT NULL REFERENCES diagrams(id) ON DELETE CASCADE,
  source_node_id INT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  target_node_id INT NOT NULL REFERENCES nodes(id) ON DELETE CASCADE,
  label TEXT
);
